FROM node:19

# set working directory
WORKDIR /usr/app/client

# add `/usr/src/app/node_modules/.bin` to $PATH
# see: https://stackoverflow.com/a/65407744
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV NODE_ENV production

# install and cache app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm ci

# add app
COPY . .

# start app
CMD ["npm", "start"]