services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig
