services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/app/scripts/docker-entrypoint.sh']
    volumes:
      - .:/usr/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/server/app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=server.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db

  api-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
