"""Refactor table names to lowercase

Revision ID: d07dd1d35e8a
Revises: f85af05ed216
Create Date: 2023-06-11 21:30:48.997431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd07dd1d35e8a'
down_revision = 'f85af05ed216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.drop_table('ProfileTable')
    op.drop_table('AccountTable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountTable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AccountTable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='AccountTable_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ProfileTable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ProfileTable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['AccountTable.id'], name='ProfileTable_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ProfileTable_pkey'),
    sa.UniqueConstraint('account_id', name='ProfileTable_account_id_key')
    )
    op.drop_table('profile')
    op.drop_table('account')
    # ### end Alembic commands ###
