name: CICD

on:
  push:
    branches: ["main"]

env:
  # see for tr: https://linuxhint.com/bash_tr_command/
  # here, it converts all uppercase in GITHUB_REPOSITORY to lowercase
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr [:upper:] [:lower:])/app

jobs:
  test:
    name: Run tests & style-checks
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        working-directory: ./api
        env:
          DATABASE_TEST_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
        run: python -m pytest "src/tests" -p no:warnings --maxfail=2
      - name: Flake8
        working-directory: ./api
        run: python -m flake8 src
      - name: Black
        working-directory: ./api
        run: python -m black src --check
      - name: isort
        working-directory: ./api
        run: python -m isort src --check-only

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${CI_PAT} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          CI_PAT: ${{ secrets.CI_PAT }}
      - name: Pull images
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build images
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file Dockerfile.prod \
            "."
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:latest